# Server
#destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less", 'config.ru', 'Gemfile', 'Gemfile.lock', 'bundle']
#port:             9001
url:              http://exacttarget.github.io/fuelux-mctheme
# local dev
#url:              http://localhost:4000

# Custom vars
current_version:  1.4.1
repo:             https://github.com/ExactTarget/fuelux-mctheme

cdn:
  css:            //www.fuelcdn.com/fuelux/3.6.4/css/fuelux.min.css

mctheme:
  css:            //www.fuelcdn.com/fuelux-mctheme/1.4.1/css/fuelux-mctheme.min.css

bootstrap:
  css:            //maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css


# To view gh-pages locally
# bundle exec jekyll serve
